# -*- coding: utf-8 -*-
"""part2_producer_consumer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4cXrIEAEqYWYXpd7YjDP8Xp0aMwdtua
"""

"""
Part 2: Producer-Consumer Problem

Producer = Baker
Consumer = Customer

A queue is used as a bread basket.
The basket has a maximum size of 5.

If the basket is full, bakers wait.
If the basket is empty, customers wait.

queue.Queue handles waiting automatically.
"""

import threading
import queue
import time
import random

BASKET_SIZE = 5
NUMBER_OF_BAKERS = 2
NUMBER_OF_CUSTOMERS = 2
BREAD_PER_BAKER = 6

basket = queue.Queue(maxsize=BASKET_SIZE)


def baker(baker_id):
    """
    Baker produces bread and puts it into the basket.
    If the basket is full, basket.put() waits automatically.
    """
    for bread_number in range(1, BREAD_PER_BAKER + 1):
        bread = f"Bread {bread_number} from Baker {baker_id}"

        if basket.full():
            print(f"Baker {baker_id}: Basket is full. Waiting...")

        basket.put(bread)
        print(f"Baker {baker_id}: Produced {bread}. Basket size = {basket.qsize()}")

        time.sleep(random.uniform(0.2, 0.6))

    print(f"Baker {baker_id}: Finished baking.")


def customer(customer_id):
    """
    Customer takes bread from the basket and eats it.
    If the basket is empty, basket.get() waits automatically.
    """
    while True:
        if basket.empty():
            print(f"Customer {customer_id}: Basket is empty. Waiting...")

        bread = basket.get()

        # None is used as a stop signal
        if bread is None:
            print(f"Customer {customer_id}: No more bread. Leaving.")
            basket.task_done()
            break

        print(f"Customer {customer_id}: Took {bread}. Basket size = {basket.qsize()}")
        time.sleep(random.uniform(0.3, 0.8))
        print(f"Customer {customer_id}: Ate {bread}")

        basket.task_done()


if __name__ == "__main__":
    baker_threads = []
    customer_threads = []

    print("Starting Producer-Consumer simulation...\n")

    # Start customers first so they wait if basket is empty
    for i in range(1, NUMBER_OF_CUSTOMERS + 1):
        thread = threading.Thread(target=customer, args=(i,))
        customer_threads.append(thread)
        thread.start()

    # Start bakers
    for i in range(1, NUMBER_OF_BAKERS + 1):
        thread = threading.Thread(target=baker, args=(i,))
        baker_threads.append(thread)
        thread.start()

    # Wait for all bakers to finish producing
    for thread in baker_threads:
        thread.join()

    # Send stop signal to each customer
    for _ in range(NUMBER_OF_CUSTOMERS):
        basket.put(None)

    # Wait until all items are processed
    basket.join()

    # Wait for all customers to finish
    for thread in customer_threads:
        thread.join()

    print("\nProducer-Consumer simulation finished.")