# -*- coding: utf-8 -*-
"""part4_thread_pool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEYwGHuvFiqezTqrDL4OJKl8UPwxrz5G
"""

"""
Part 4: Thread Pool

This program compares:
1. Sequential execution
2. Parallel execution using ThreadPoolExecutor

There are 10 tasks.
Each task sleeps for 1 second to simulate work.

Sequential execution runs one task at a time.
Parallel execution runs multiple tasks at the same time.
"""

import time
from concurrent.futures import ThreadPoolExecutor

NUMBER_OF_TASKS = 10
NUMBER_OF_WORKERS = 4


def task(task_id):
    """
    A simple task that simulates work using sleep.
    """
    print(f"Task {task_id} started")
    time.sleep(1)
    print(f"Task {task_id} finished")
    return task_id


def run_sequential():
    """
    Runs tasks one by one.
    """
    print("Running tasks sequentially...\n")

    start_time = time.perf_counter()

    for i in range(1, NUMBER_OF_TASKS + 1):
        task(i)

    end_time = time.perf_counter()
    total_time = end_time - start_time

    return total_time


def run_parallel():
    """
    Runs tasks using a thread pool.
    """
    print("Running tasks in parallel using ThreadPoolExecutor...\n")

    start_time = time.perf_counter()

    with ThreadPoolExecutor(max_workers=NUMBER_OF_WORKERS) as executor:
        executor.map(task, range(1, NUMBER_OF_TASKS + 1))

    end_time = time.perf_counter()
    total_time = end_time - start_time

    return total_time


if __name__ == "__main__":
    sequential_time = run_sequential()

    print("\n" + "-" * 40 + "\n")

    parallel_time = run_parallel()

    speedup = sequential_time / parallel_time

    print("\nResults:")
    print(f"Sequential time: {sequential_time:.2f} seconds")
    print(f"Parallel time:   {parallel_time:.2f} seconds")
    print(f"Speedup:         {speedup:.2f}x faster")
    print(f"Threads used:    {NUMBER_OF_WORKERS}")