# -*- coding: utf-8 -*-
"""part3_dining_philosophers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCZ-pLgD5sPhTHP0-e8ZNHdgi0Ffs_Y3
"""

"""
Part 3: Dining Philosophers Problem

There are:
- 3 philosophers
- 3 forks

Each philosopher needs 2 forks to eat.

Deadlock prevention method used:
Each philosopher always picks the lower-numbered fork first,
then the higher-numbered fork.

This prevents circular waiting, so deadlock does not happen.
"""

import threading
import time
import random

NUMBER_OF_PHILOSOPHERS = 3
EATING_ROUNDS = 3

forks = [threading.Lock() for _ in range(NUMBER_OF_PHILOSOPHERS)]


def philosopher(philosopher_id):
    """
    Each philosopher thinks, picks up two forks, eats, and repeats.
    """
    left_fork = philosopher_id
    right_fork = (philosopher_id + 1) % NUMBER_OF_PHILOSOPHERS

    # Deadlock prevention:
    # Always pick lower-numbered fork first.
    first_fork = min(left_fork, right_fork)
    second_fork = max(left_fork, right_fork)

    for round_number in range(1, EATING_ROUNDS + 1):
        print(f"Philosopher {philosopher_id}: Thinking...")
        time.sleep(random.uniform(0.5, 1.0))

        print(
            f"Philosopher {philosopher_id}: Trying to pick forks "
            f"{first_fork} and {second_fork}"
        )

        with forks[first_fork]:
            print(f"Philosopher {philosopher_id}: Picked fork {first_fork}")

            time.sleep(0.1)

            with forks[second_fork]:
                print(f"Philosopher {philosopher_id}: Picked fork {second_fork}")
                print(f"Philosopher {philosopher_id}: Eating round {round_number}...")

                time.sleep(random.uniform(0.5, 1.0))

                print(f"Philosopher {philosopher_id}: Finished eating round {round_number}")

            print(f"Philosopher {philosopher_id}: Put down fork {second_fork}")

        print(f"Philosopher {philosopher_id}: Put down fork {first_fork}")
        print()

    print(f"Philosopher {philosopher_id}: Done eating.")


if __name__ == "__main__":
    threads = []

    print("Starting Dining Philosophers simulation...\n")

    for i in range(NUMBER_OF_PHILOSOPHERS):
        thread = threading.Thread(target=philosopher, args=(i,))
        threads.append(thread)
        thread.start()

    for thread in threads:
        thread.join()

    print("\nDining Philosophers simulation finished without deadlock.")