# -*- coding: utf-8 -*-
"""part1_race_condition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNeE8S_7078r0EBUrrfFeyagZ87wb2rw
"""

"""
Part 1: Race Condition

This program shows:
1. Race condition without a lock
2. Correct synchronization with a lock

Three threads increment a shared counter 1000 times each.
Expected final counter value = 3000
"""

import threading
import time

counter = 0
lock = threading.Lock()

INCREMENTS_PER_THREAD = 1000
NUMBER_OF_THREADS = 3


def increment_without_lock():
    """
    This function increments the global counter without using a lock.
    A small sleep is added to make the race condition easier to see.
    """
    global counter

    for _ in range(INCREMENTS_PER_THREAD):
        temp = counter
        time.sleep(0.00001)  # Forces thread switching
        counter = temp + 1


def increment_with_lock():
    """
    This function increments the global counter safely using a lock.
    Only one thread can change the counter at a time.
    """
    global counter

    for _ in range(INCREMENTS_PER_THREAD):
        with lock:
            temp = counter
            time.sleep(0.00001)
            counter = temp + 1


def run_without_lock():
    global counter
    counter = 0

    threads = []

    print("Running WITHOUT lock...")

    for i in range(NUMBER_OF_THREADS):
        thread = threading.Thread(target=increment_without_lock)
        threads.append(thread)
        thread.start()

    for thread in threads:
        thread.join()

    print("Expected counter value: 3000")
    print("Actual counter value without lock:", counter)
    print()


def run_with_lock():
    global counter
    counter = 0

    threads = []

    print("Running WITH lock...")

    for i in range(NUMBER_OF_THREADS):
        thread = threading.Thread(target=increment_with_lock)
        threads.append(thread)
        thread.start()

    for thread in threads:
        thread.join()

    print("Expected counter value: 3000")
    print("Actual counter value with lock:", counter)
    print()


if __name__ == "__main__":
    run_without_lock()
    run_with_lock()